app/basket/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, SubmitField, TelField, EmailField
)
from wtforms.validators import (
    DataRequired, Length, Regexp, Email
)


class PlaceAnOrder(FlaskForm):
    name = StringField('Ваше имя', validators=
                               [DataRequired(
                                   message='Поле не может быть пустым'),
                                Length(
                                    min=3,
                                    max=50,
                                    message='Ввод разрешен: от 3, до 50 символов'
                                ),
                                Regexp(
                                    r'^[а-яА-Яa-zA-Z0-9\s]+$',
                                    message='Введен неподдерживаемый символ'
                                )
                               ]
    )
    email = EmailField('Ваш email', validators=
                        [DataRequired(
                            message='Поле не может быть пустым'
                        ),
                         Email(
                            message='Не верный адресс'  
                        )]
    )
    
    phone_number = TelField('Номер телефона', validators=[
        DataRequired(message='Поле не может быть пустым'),
        Length(min=10, max=15, message=
               'Номер телефона должен быть от 10 до 15 символов'
        ),
        Regexp(r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$', message=
               'Некорректный формат номера телефона'
        )]
    )
    
    submit = SubmitField('Заказать!')

app/basket/__init__.py
from flask import Blueprint

bp = Blueprint('basket', __name__, url_prefix='/basket')

from app.basket import routes, forms

app/basket/routes.py
import json

from flask import (
    render_template, url_for, request, make_response, redirect, abort,
    flash
)
from app.models import Products, HistorySales, HistoryProducts
from app import db
from app.basket import bp
from app.email import send_mail, msg_basket_for_admin, msg_basket_for_user
from app.basket.forms import PlaceAnOrder
from config import Config


@bp.route('/')
def index():
    form = PlaceAnOrder()
    products_and_count = list()
    data_basket = request.cookies.get('data_basket')
    if data_basket:
        data_basket = json.loads(data_basket)
        basket_items = list(data_basket.items())
        products_and_count = [
            (Products.query.get(int(i[0])), i[1]) for i in basket_items
        ]
    
    return render_template(
        'basket/basket.html',
        products_and_count=products_and_count,
        form=form,
        title='Корзина',
        active_page='basket.index'
    )
    
    
@bp.route('/delete-product', methods=['POST'])
def delete_product():
    response = make_response(redirect(url_for('basket.index')))
    data_id = request.form.get('get_id')
    data_basket_json = request.cookies.get('data_basket')
    if data_basket_json:
        data_basket = json.loads(data_basket_json)
        if len(data_basket.keys()) == 1:
            response.delete_cookie('data_basket')
        else:
            del data_basket[data_id]
            data_basket_json = json.dumps(data_basket)
            response.set_cookie(
                'data_basket',
                data_basket_json,
                max_age=60*60*24
            )
        return response
    return redirect(url_for('basket.index'))


@bp.route('/update-product-in-basket', methods=['POST'])
def update_product_in_basket():
    product_id = request.form.get('get_id')
    cost = request.form.get('cost')
    response = make_response(redirect(url_for('basket.index')))
    if product_id and cost:
        data_basket_json = request.cookies.get('data_basket')
        if data_basket_json:
            data_basket = json.loads(data_basket_json)
            
            if data_basket.get(product_id) == cost:
                return redirect(url_for('basket.index'))

            data_basket[product_id] = cost
            data_basket_json = json.dumps(data_basket)
            response.set_cookie(
                'data_basket',
                data_basket_json,
                max_age=60*60*24
            )
            flash('Товары успешно обновлены!')
            return response
                
    return abort(404)


@bp.route('by-basket', methods=['POST'])
def by_basket():
    with open('switch.json', encoding='utf-8') as file:
        data = json.load(file)
        status_basket = int(data['check_on_or_off_basket'])
        if not status_basket:
            flash("Покупка товаров временно не возможна!")
            return redirect(url_for('basket.index'))

    form = PlaceAnOrder()
    def query_products(p_id, count):
        product = Products.query.filter(Products.id == p_id).first()
        product_dict = {
           'name': product.name,
           'about': product.about,
           'price': product.price,
           'count': count,
           'total': int(count) * int(product.price),
           'section': product.section.name,
           'sub_section': product.sub_section.name,
           'link': f'{Config.NEW_DOMAIN2}/{product.id}',
           'img_link': Config.NEW_DOMAIN2.rstrip('/') + url_for(
               'static', filename=product.img_link
               )
        }
        return product_dict
        
    
    
    data_basket_json = request.cookies.get('data_basket')
    if  data_basket_json:
        data_basket = json.loads(data_basket_json)
        if not form.validate_on_submit():
            basket_items = list(data_basket.items())
            products_and_count = [
            (Products.query.get(int(i[0])), i[1]) for i in basket_items
            ]
            
            return render_template(
                    'basket/basket.html',
                    form=form,
                    products_and_count=products_and_count
            )

        products = tuple(map(
            lambda items: query_products(items[0], items[1]),
            data_basket.items()
            )
        )
        name = form.name.data
        email = form.email.data
        phone = form.phone_number.data
        total_sum = sum(map(lambda x: x['total'], products))
        
        try:
            sales = HistorySales()
            for product in products:
                history = HistoryProducts()
                history.name_user = name
                if product['about']:
                    history.about_product = product['about']
                else:
                    history.about_product = 'Нет описания'
                history.email_user = email
                history.phone_user = str(phone)
                history.name_product = product['name']
                history.name_product = product['name']
                history.price = product['price']
                history.total_price = int(product['total'])
                history.count = int(product['count'])
                history.img_link = product['img_link']
                history.section = product['section']
                history.sub_section = product['sub_section']
                history.link_to_product = product['link']
                sales.h_prod.append(history)
            db.session.add(sales)
            db.session.commit()
        except Exception as err:
            db.session.rollback()
            print(err)
        finally:
            order_id = HistorySales.query.order_by(
                HistorySales.id.desc()
            ).first()
            order_id = order_id.id
        
        response = make_response(render_template(
            'basket/by.html',
            order_id=order_id
            )
        )
        
        admin_msg = msg_basket_for_admin(order_id, name, email, phone, total_sum, products)
        user_msg = msg_basket_for_user(order_id, name, total_sum, products)
        send_mail(
            'Заказ в магазине!',
            [Config.MAIL_USERNAME],
            html_body=admin_msg
        )
        send_mail(
            'Tomato Shop',
            [email],
            html_body=user_msg
        )
        response.delete_cookie('data_basket')
        return response
    
    flash('Ваша корзина пустая!')
    return redirect(url_for('basket.index'))

app/templates/basket/_scripts.html
<script src="{{ url_for('static', filename='js/price_counts_in_basket.js') }}"></script>
<script src="{{ url_for('static', filename='js/anim_button.js') }}"></script>

app/templates/basket/basket.html
{% extends "base.html" %}


{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% for message in get_flashed_messages() %}
  <div class="alert alert-danger" style="color: red;" role="alert">
    {{ message }}
  </div>
  {% endfor %}
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-xl-4 col-md-6">
        {% for product, count in products_and_count %}
          {% if product.is_active %}
            <div>
              <a href="{{ url_for('main.index') }}{{ product.id }}" class="text-decoration-none text-dark" rel="noopener noreferrer">      
                <h2>{{ product.name }}</h2>
              </a>
              <p>Цена: {{ product.price }} р.</p>
              <p class="price-element" style="display: none;">{{ product.price }}</p>
              <form action="{{ url_for('basket.update_product_in_basket') }}" method="post">
                <div class="row justify-content-left">
                  <div class="col-xl-4 col-md-4 col-sm-4">
                    <input type="number" step="1" min="1" max="100" value="{{ count }}" class="quantity form-control" name="cost"/>
                  </div>
                    <input type="hidden" name="get_id" value="{{ product.id }}">
                  <div class="col-xl-4 col-md-4 col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Изменить количество">
                  </div>
                </div>
              </form> 
              <p class="total-cost">Общая стоимость: <span class="total-cost-value">{{ product.price | int * count | int }} р.</span></p>
              <a href="{{ url_for('main.index') }}{{ product.id }}" rel="noopener noreferrer">      
                <div>
                  <img src="{{ url_for('static', filename=product.img_link) }}" class="img-fluid" alt="product_img">
                </div>
              </a>
              <form method="post" action="{{ url_for('basket.delete_product') }}">
                <input type="hidden" name="get_id" value="{{ product.id }}">
                <button class="btn btn-primary mt-2" type="submit">Удалить</button>
              </form>
            </div>
            <hr>
          {% endif %}
        {% endfor %}
      </div>
      <div class="col-xl-4 col-md-6">
        <div>
          <p class="h2" id="total-cost-all-products">Итого: <span id="total-cost-all-products-value">0 р.</span></p>
        </div>
        <h2>Оформить Заказ!</h2>
        <form method="post" action="{{ url_for('basket.by_basket') }}" id="myForm" onsubmit="handleSubmit(event)">
          {{ form.hidden_tag() }}
          <div class="mb-3">
            {{ form.name.label(class_="form-label") }}<br>
            {{ form.name(class_="form-control") }}
            {% for error in form.name.errors %}
              <div class="alert alert-danger" role="alert", style="color:red">
                {{ error }}
              </div>
            {% endfor %}
          </div>
          <div class="mb-3">
            {{ form.email.label(class_="form-label") }}<br>
            {{ form.email(class_="form-control") }}
            {% for error in form.email.errors %}
              <div class="alert alert-danger" role="alert", style="color:red">
                {{ error }}
              </div>
            {% endfor %}
          </div>
          <div class="mb-3">
            {{ form.phone_number.label(class_="form-label") }}<br>
            {{ form.phone_number(class_="form-control") }}
            {% for error in form.phone_number.errors %}
              <div class="alert alert-danger" role="alert", style="color:red">
                {{ error }}
              </div>
            {% endfor %}
          </div class="mb-3">
          <div>
            <a href="{{ url_for('main.sell_and_by') }}">Перед заказом ознакомьтесь с условиями "Оплаты и Доставки!</a>
            <div class="mb-3">
              {{ form.submit(class_="btn btn-primary mt-2", id="submitButton") }}
            </div>
            <button class="btn btn-primary" type="button" id="loadingButton" disabled style="display: none;">
              <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
              Загрузка...
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {% include 'basket/_scripts.html' %}
{% endblock %}

app/templates/basket/by.html
{% extends "base.html" %}


{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="justify-content-center">
    <h1>Спасибо за покупку</h1>
    <h4>Номер вашего заказа: {{ order_id }}</h4>
    <p>
      Сохраните номер вашего заказа, пержде чем закрыть эту страницу.
    </p>
    <p>
      Благодарим за заказ!<br>Мы стремимся быть лучшими, находя и выращивая для
      вас самые интересныеивкусные томаты. Спасибо, что выбрали нас.
    </p>
    <p>
      Подробности о вашем заказе были отправлены на указанную вами почту.<br>
      Также, позже мы свяжемся с вами по этой почте, для уточнения деталей
      заказа.
    </p>
    <p>
      Внимание!!! Письмо может попасть в папку спам! Не забудьте проверить
      папку спам в вашем почтовом ящике!
    </p>
    <p>
      Если вы так и не получили письмо, можете связаться с нами в раздле:
      <a href="{{ url_for('main.contacts') }}">Контакты</a>. Не забудьте
      сообщить нам номер вашего заказа.
    </p>
{% endblock %}