app/slug/__init__.py
from flask import Blueprint

bp = Blueprint('slug', __name__)

from app.slug import routes

app/slug/routes.py
import json

from flask import (
    render_template, url_for, request, make_response, redirect, abort,
    flash
)
from app.models import Products
from app.slug import bp


@bp.route('/<int:id>')
def index(id):
    data_basket = request.cookies.get('data_basket')
    if data_basket:
        data_basket = json.loads(data_basket)
    product = Products.query.get(id)
    if product and product.is_active:
        return render_template(
            'slug/product_card.html',
            product=product,
            data_basket=data_basket,
            p_id=str(id),
            title='Product'
        )
    abort(404)


@bp.route('/add-to-basket', methods=['POST'])
def add_to_basket():
    product_id = request.form.get('get_id')
    cost = request.form.get('cost')
    response = make_response(redirect(url_for('slug.index', id=product_id)))
    if product_id and cost:
        data_basket_json = request.cookies.get('data_basket')
        if data_basket_json:
            data_basket = json.loads(data_basket_json)
            
            if data_basket.get(product_id) == cost:
                return redirect(url_for('slug.index', id=product_id))

            data_basket[product_id] = cost
            data_basket_json = json.dumps(data_basket)
            response.set_cookie(
                'data_basket',
                data_basket_json,
                max_age=60*60*24
            )
            flash('Товар успешно добавлен в корзину!')
            return response
                
        data_basket = {product_id: cost}
        data_basket_json = json.dumps(data_basket)
        response.set_cookie(
            'data_basket',
            data_basket_json,
            max_age=60*60*24 
        )
        flash('Товар успешно добавлен в корзину!')
        return response
                
    return abort(404)

app/templates/slug/_scripts.html
<script src="{{ url_for('static', filename='js/price_count.js') }}"></script>

app/templates/slug/product_card.html
{% extends "base.html" %}


{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" style="color: red;" role="alert">
      {{ message }}
    </div>
  {% endfor %}
  <div id="item-list">
    <div>
      <h2>{{ product.name }}</h2>
      <p>Цена: {{ product.price }} р.</p>
      <p type="hidden" id="priceElement" style="display: none;">{{ product.price }}</p>
      {% if product.about %}
        <p>Описание: {{ product.about }}</p>
      {% endif %}
      <div>
        <img src="{{ url_for('static', filename=product.img_link) }}" class="img-fluid" style="max-width: 600px; width: 100%; height: auto;" alt="product_img">
      </div>
    </div>
  </div>
  <div>
    <form action="{{ url_for('slug.add_to_basket') }}" method="post">
      <div class="row">
        <div class=" col-sm-2">
          {% if data_basket and p_id in data_basket %}
            <input class="form-control mb-3 mt-3" type="number" step="1" min="1" max="100" value="{{data_basket[p_id]}}" id="quantity" name="cost"/>
          {% else %}
            <input class="form-control mb-3 mt-3" type="number" step="1" min="1" max="100" value="1" id="quantity" name="cost"/>
          {% endif %}
          <input type="hidden" name="get_id" value="{{ product.id }}">
          <input class="btn btn-primary mb-2" type="submit" value="Добавить в корзину">
        </div>
      </div>
    </form>
    {% if data_basket and p_id in data_basket %}
      <p id="total-cost">Общая стоимость: <span id="total-cost-value">{{ product.price | int * data_basket[p_id] | int }} р.</span></p>
    {% else %}
      <p id="total-cost">Общая стоимость: <span id="total-cost-value">{{ product.price | int }} р.</span></p>
    {% endif %}
  </div>
{% endblock %}


{% block scripts %}
  {% include 'slug/_scripts.html' %}
{% endblock %}